name: "Prepare Python environment"
description: "Set up Python and install dependencies"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.10.0
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.6.8"
        enable-cache: true
        cache-dependency-glob: "uv.lock"
    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"